spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.cbhfjgnihkppdbwdqbmz
spring.datasource.password=Idhayakumar@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085
spring.jackson.property-naming-strategy=SNAKE_CASE